// Configurações do site e dados dos produtos
const siteConfig = {
  site: {
    nome: "Bella Moda",
    tagline: "Moda feminina exclusiva com renovação semanal",
    whatsapp: "5511999999999", // SUBSTITUA pelo seu número
    endereco: "Rua das Flores, 123 - Centro",
    instagram: "@bellamoda",
  },

  produtos: [
    {
      id: 1,
      nome: "Vestido Midi Floral Primavera",
      categoria: "Vestidos",
      preco: 189.9,
      precoOriginal: 249.9,
      desconto: 24,
      novo: true,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1566479179817-c0b5b4b4b1e8?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop",
      descricao:
        "Vestido midi com estampa floral delicada, perfeito para a primavera. Confeccionado em tecido fluido de alta qualidade, com caimento impecável que valoriza a silhueta feminina.",
      descricaoDetalhada:
        "Este vestido midi é a peça perfeita para quem busca elegância e conforto. A estampa floral exclusiva foi desenvolvida especialmente para nossa coleção, trazendo um toque romântico e sofisticado.",
      detalhes: [
        "Tecido: Crepe georgette premium",
        "Forro: 100% viscose",
        "Comprimento: Midi (altura do joelho)",
        "Modelagem: Solta, com amarração na cintura",
        "Cuidados: Lavar à mão ou lavagem delicada",
        "Origem: Confecção nacional",
      ],
      tamanhos: ["P", "M", "G", "GG"],
      cores: ["Floral Rosa", "Floral Azul", "Floral Verde"],
      avaliacoes: { nota: 4.8, total: 127 },
      ocasioes: ["Trabalho", "Encontros", "Eventos casuais", "Passeios"],
    },
    {
      id: 2,
      nome: "Blusa Cropped Renda Delicada",
      categoria: "Blusas",
      preco: 89.9,
      precoOriginal: 119.9,
      desconto: 25,
      novo: false,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=500&fit=crop",
      descricao:
        "Blusa cropped em renda delicada com forro interno. Peça versátil que combina com saias, calças e shorts.",
      descricaoDetalhada: "Nossa blusa cropped em renda é a combinação perfeita entre delicadeza e modernidade.",
      detalhes: [
        "Material: Renda francesa + forro viscose",
        "Modelagem: Cropped ajustado",
        "Manga: Curta com acabamento em renda",
        "Fechamento: Zíper invisível nas costas",
        "Cuidados: Lavagem delicada",
      ],
      tamanhos: ["P", "M", "G"],
      cores: ["Branco", "Off-white", "Nude"],
      avaliacoes: { nota: 4.6, total: 89 },
      ocasioes: ["Trabalho", "Balada", "Encontros", "Eventos"],
    },
    {
      id: 3,
      nome: "Saia Plissada Alta Costura",
      categoria: "Saias",
      preco: 129.9,
      precoOriginal: 169.9,
      desconto: 24,
      novo: true,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1583496661160-fb5886a13d27?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1583496661160-fb5886a13d27?w=400&h=500&fit=crop",
      descricao: "Saia plissada com pregas marcadas e caimento perfeito. Cintura alta que alonga a silhueta.",
      descricaoDetalhada: "Esta saia plissada é uma verdadeira obra de arte da costura.",
      detalhes: [
        "Tecido: Crepe premium com elastano",
        "Modelagem: Cintura alta",
        "Comprimento: Midi (abaixo do joelho)",
        "Pregas: Marcadas e fixadas",
        "Fechamento: Zíper lateral invisível",
      ],
      tamanhos: ["P", "M", "G", "GG"],
      cores: ["Preto", "Marinho", "Caramelo", "Vinho"],
      avaliacoes: { nota: 4.9, total: 156 },
      ocasioes: ["Trabalho", "Eventos formais", "Reuniões", "Jantares"],
    },
    {
      id: 4,
      nome: "Conjunto Blazer + Short Executivo",
      categoria: "Conjuntos",
      preco: 259.9,
      precoOriginal: 329.9,
      desconto: 21,
      novo: false,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop",
      descricao: "Conjunto executivo moderno com blazer estruturado e short alfaiataria.",
      descricaoDetalhada: "Este conjunto representa o equilíbrio perfeito entre profissionalismo e modernidade.",
      detalhes: [
        "Blazer: Alfaiataria com forro completo",
        "Short: Cintura alta com pregas frontais",
        "Tecido: Gabardine stretch premium",
        "Botões: Madrepérola natural",
        "Bolsos: Funcionais no blazer",
      ],
      tamanhos: ["P", "M", "G", "GG"],
      cores: ["Preto", "Marinho", "Cinza", "Bege"],
      avaliacoes: { nota: 4.7, total: 203 },
      ocasioes: ["Trabalho", "Reuniões", "Apresentações", "Eventos corporativos"],
    },
    {
      id: 5,
      nome: "Body Manga Longa Elegante",
      categoria: "Bodies",
      preco: 79.9,
      precoOriginal: 99.9,
      desconto: 20,
      novo: true,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1566479179817-c0b5b4b4b1e8?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=500&fit=crop",
      descricao:
        "Body manga longa com gola alta e fechamento discreto. Tecido com elastano para perfeito ajuste ao corpo.",
      descricaoDetalhada: "Este body é a peça coringa do seu guarda-roupa.",
      detalhes: [
        "Tecido: Viscose com elastano",
        "Gola: Alta e ajustada",
        "Manga: Longa com punho ajustado",
        "Fechamento: Colchetes na parte inferior",
        "Modelagem: Justa ao corpo",
      ],
      tamanhos: ["P", "M", "G"],
      cores: ["Preto", "Branco", "Nude", "Vinho"],
      avaliacoes: { nota: 4.5, total: 78 },
      ocasioes: ["Trabalho", "Casual", "Balada", "Sobreposição"],
    },
    {
      id: 6,
      nome: "Calça Wide Leg Premium",
      categoria: "Calças",
      preco: 149.9,
      precoOriginal: 199.9,
      desconto: 25,
      novo: false,
      destaque: true,
      imagens: [
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=700&fit=crop",
        "https://images.unsplash.com/photo-1583496661160-fb5886a13d27?w=500&h=700&fit=crop",
      ],
      imagemPrincipal: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop",
      descricao: "Calça wide leg de cintura alta com caimento fluido. Modelagem que alonga a silhueta.",
      descricaoDetalhada: "Nossa calça wide leg é sinônimo de elegância e conforto.",
      detalhes: [
        "Tecido: Crepe com elastano",
        "Modelagem: Wide leg, cintura alta",
        "Comprimento: Longo (até o chão)",
        "Bolsos: Laterais funcionais",
        "Fechamento: Zíper lateral + botão",
      ],
      tamanhos: ["P", "M", "G", "GG"],
      cores: ["Preto", "Caramelo", "Verde Militar", "Terracota"],
      avaliacoes: { nota: 4.8, total: 134 },
      ocasioes: ["Trabalho", "Casual chic", "Eventos", "Viagens"],
    },
  ],
}
